name: "RuboCop Lint"
description: "Run RuboCop linting (assumes Ruby is already set up)"
author: "84codes"

runs:
  using: "composite"
  steps:
    - name: Run RuboCop
      shell: bash
      run: bundle exec rubocop --format github

branding:
  icon: "check-circle"
  color: "purple"
