name: Ruby CI

on:
  workflow_call:
    inputs:
      ruby-version:
        description: "The Ruby ruby-version to use"
        default: ".ruby-version"
        required: false
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.ORG_GITHUB_TOKEN_FOR_CI }}
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test
