name: Ruby CI

on:
  workflow_call:
    inputs:
      run:
        description: "The command to run (e.g. bundle exec rake)"
        default: "bundle exec rake"
        required: false
        type: string
      ruby-version:
        description: "The Ruby ruby-version to use"
        default: ".ruby-version"
        required: false
        type: string
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry
      pkg-github-com-user:
        description: "GitHub username for rubygems.pkg.github.com auth"
        default: "machine-user-84"
        required: false
        type: string
      postgres:
        description: "Start PostgreSQL in the GitHub Actions VM"
        default: false
        required: false
        type: boolean
      postgres-env-key:
        description: "Name of the environment variable with the Postgres URL"
        default: "DATABASE_URL"
        required: false
        type: string
      ruby-lint:
        description: "Run RuboCop using https://github.com/reviewdog/action-rubocop"
        default: false
        required: false
        type: boolean
      bundle-frozen:
        description: "Value to use for BUNDLE_FROZEN environment variable"
        default: true
        required: false
        type: boolean
      bundler-cache:
        description: "Value to use for the setup-ruby input 'bundler-cache'"
        default: true
        required: false
        type: boolean
      cache-version:
        description: "Value to use for the setup-ruby input 'cache-version'"
        default: "0"
        required: false
        type: string
    secrets:
      github-token:
        description: "GitHub token for private repo dependencies"
        required: false
      repo-github-token:
        description: "The repo scoped token generated by GitHub Actions"
        required: false
      pkg-github-com:
        description: "Value to use for BUNDLE_RUBYGEMS__PKG__GITHUB__COM"
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Start PostgreSQL if requested
        if: inputs.postgres
        uses: 84codes/postgres@main
        with:
          env-key: ${{ inputs.postgres-env-key }}

      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_FROZEN: ${{ inputs.bundle-frozen }}
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.github-token }}
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ inputs.pkg-github-com-user }}:${{ secrets.pkg-github-com }}
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: ${{ inputs.bundler-cache }}
          cache-version: ${{ inputs.cache-version }}

      - run: ${{ inputs.run }}
  lint:
    if: inputs.ruby-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout project code
        uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: ${{ inputs.bundler-cache }}
          cache-version: ${{ inputs.cache-version }}
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.github-token }}

      - uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.repo-github-token }}
          level: warning
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-check' || 'github-check' }}
          rubocop_version: gemfile
          use_bundler: true
          skip_install: true
