name: Ruby CI

on:
  workflow_call:
    inputs:
      ruby-version:
        description: "The Ruby ruby-version to use"
        default: ".ruby-version"
        required: false
        type: string
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry
      pkg-github-com-user:
        description: "GitHub username for rubygems.pkg.github.com auth"
        default: "machine-user-84"
        required: false
        type: string
      postgres:
        description: "Start PostgreSQL in the GitHub Actions VM"
        default: false
        required: false
        type: boolean
      postgres-env-key:
        description: "Name of the environment variable with the Postgres URL"
        default: "ELEPHANTSQL_URL"
        required: false
        type: string
      reviewdog:
        description: "Enable code coverage check with https://github.com/reviewdog/action-setup"
        default: false
        required: false
        type: boolean
    secrets:
      github-token:
        description: "GitHub token for private repo dependencies"
        required: false
      reviewdog-github-token:
        description: "The repo scoped token generated by GitHub Actions"
        required: false
      pkg-github-com:
        description: "Value to use for BUNDLE_RUBYGEMS__PKG__GITHUB__COM"
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start PostgreSQL if requested
        if: inputs.postgres
        uses: 84codes/postgres@main
        with:
          env-key: ${{ inputs.postgres-env-key }}

      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.github-token }}
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ inputs.pkg-github-com-user }}:${{ secrets.pkg-github-com }}
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test

      - name: Setup reviewdog
        if: inputs.reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Check code coverage with reviewdog
        if: inputs.reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.reviewdog-github-token }}
        run: |
          git fetch
          reviewdog -reporter=github-pr-review -runners=undercover
