name: Ruby CI

on:
  workflow_call:
    inputs:
      ruby-version:
        description: "The Ruby ruby-version to use"
        default: ".ruby-version"
        required: false
        type: string
    secrets:
      github-token:
        description: "GitHub token for private repo dependencies"
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.github-token }}
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Checkout tools
        uses: actions/checkout@v2
        with:
          repository: 84codes/tools
          token: ${{ secrets.ORG_GITHUB_TOKEN_FOR_CI }}
          path: tools

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Lint
        uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rubocop_flags: -c tools/.rubocop.yml -DEPS
          level: warning
          reporter: github-pr-review
          rubocop_extensions: rubocop-gitlab-security rubocop-performance rubocop-minitest rubocop-eightyfourcodes
