name: Ruby CI

on:
  workflow_call:
    inputs:
      ruby-version:
        description: "The Ruby ruby-version to use"
        default: ".ruby-version"
        required: false
        type: string
    secrets:
      github-token:
        description: "GitHub token for private repo dependencies"
        required: false
      pkg-github-com:
        description: "Value to use for BUNDLE_RUBYGEMS__PKG__GITHUB__COM"
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.github-token }}
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.pkg-github-com }}
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test
