name: Sentry release

on:
  workflow_call:
    inputs:
      sentry-org:
        description: "The Sentry org to use"
        default: "84codes"
        required: false
        type: string
      sentry-project:
        description: "The Sentry project to use"
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      branch:
        description: "The branch to checkout"
        default: ${{ github.event.repository.default_branch }}
        required: false
        type: string
    secrets:
      sentry-token:
        description: "Sentry auth token"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
          ref: ${{ inputs.branch }}
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry-token }}
          SENTRY_ORG: ${{ inputs.sentry-org }}
          SENTRY_PROJECT: ${{ inputs.sentry-project }}
        with:
          environment: production
          ignore_missing: true
          ignore_empty: true
